---
name: module3_task3

on:
  push:
    branches:
      - main

    tags:
      - '*'

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: installing Hugo
        run: cd module3_task3 && ./setup.sh

      - name: install the Markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint the files
        run: cd module3_task3 && make lint

      - name: Tests
        run: cd module3_task3 && make test

      - name: Archives the files
        run: cd module3_task3 && make package

      - name: validate the Makefile
        run: cd module3_task3 && make help && make build

  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: install the Markdownlint
        run: npm install -g markdownlint-cli

      - name: Install Hugo
        run: cd module3_task3 && ./setup.sh

      - name: Archives the files
        run: cd module3_task3 && make package

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          files: ./module3_task3/awesome-website.zip
          body_path: ./module3_task3/DEPLOY.md
