# Ensure build-docker target is present in the Makefile
make help 2>&1 | grep -q 'build-docker' && echo OK

# Check if the Docker image awesome:build exists
docker inspect awesome:build >/dev/null && echo PRESENT || echo ABSENT

# Clean, build the Docker image, and check if it exists
make clean build-docker && echo OK
docker inspect awesome:build >/dev/null && echo PRESENT || echo ABSENT

# Validate that any goal of the Makefile runs successfully when only Docker is available
# Ensure go, hugo, and golangci-lint are not found
which go hugo golangci-lint || echo "not found"

# Check if the necessary files and directories exist
ls -1 ./dist ./coverage-units.out ./coverage-integrations.out || echo "not found"

# Clean, lint, build, and test
make clean lint build test && echo OK

# Verify that the necessary files and directories are created
ls -1 ./dist ./coverage-units.out ./coverage-integrations.out || echo "not found"
